# Generated by Django 4.2.7 on 2023-11-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('organisation', models.CharField(max_length=50)),
                ('complete_status', models.BooleanField(default=False)),
                ('date_last_saved', models.DateField(auto_now=True)),
            ],
        ),
    ]
