# Generated by Django 4.2.7 on 2023-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_question_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('RV', 'reviewed'), ('AW', 'answered'), ('UA', 'unanswered')], default='UA', max_length=3),
        ),
    ]
