# Generated by Django 4.2.7 on 2023-12-14 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='assesment_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.assesment'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.question'),
        ),
    ]
