# Generated by Django 4.2.7 on 2023-12-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_answer_assesment_id_alter_answer_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('organisation', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='answer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.answer'),
        ),
    ]
