# Generated by Django 4.2.7 on 2023-12-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_collaborator_delete_phase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='answer_id',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='answers',
            field=models.ManyToManyField(to='base.answer'),
        ),
    ]
