# Generated by Django 4.2.7 on 2023-12-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_collaborator_answer_id_collaborator_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=128)),
                ('questions', models.ManyToManyField(to='base.question')),
            ],
        ),
    ]
