# Generated by Django 4.2.7 on 2024-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_reference_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='date_last_saved',
        ),
        migrations.AddField(
            model_name='question',
            name='job_list',
            field=models.JSONField(default=list),
        ),
    ]
