# Generated by Django 4.2.7 on 2024-01-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_assesment_date_last_saved_question_job_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='date_last_saved',
            field=models.DateField(auto_now=True),
        ),
    ]
