# Generated by Django 4.2.7 on 2024-02-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_question_question_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_reference_text',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
