# Generated by Django 4.2.7 on 2024-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_question_question_reference_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='discipline',
            field=models.CharField(default='Geen baanbeschrijving', max_length=40),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
