# Generated by Django 4.2.7 on 2024-02-25 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_collaborator_discipline_alter_collaborator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='ultimately_responsble',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assesment',
            name='user_group',
            field=models.ManyToManyField(related_name='related_assesment', to=settings.AUTH_USER_MODEL),
        ),
    ]
