# Generated by Django 5.0.4 on 2024-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_answer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_context',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_instruction',
            field=models.TextField(default=''),
        ),
    ]
