# Generated by Django 5.0.4 on 2024-05-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_law_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phas4Answer',
            new_name='Phase4Answer',
        ),
    ]
