# Generated by Django 4.2.7 on 2024-05-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_phas4answer_phase4answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cluster_name', models.CharField(default='Default cluster', max_length=100)),
                ('subclusters', models.JSONField(null=True)),
            ],
        ),
    ]
