# Generated by Django 5.0.4 on 2024-10-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_lawcluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
