# Generated by Django 5.0.4 on 2024-10-25 10:06

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_question_question_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='assesment',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='assesment_id',
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('organisation', models.CharField(max_length=50)),
                ('complete_status', models.BooleanField(default=False)),
                ('date_last_saved', models.DateField(auto_now=True)),
                ('ultimately_responsible', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(default=base.models.user_pk_sentinel, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ManyToManyField(related_name='related_assessment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='assessment_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.assessment'),
        ),
        migrations.AddField(
            model_name='law',
            name='assessment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.assessment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Assesment',
        ),
    ]
