# Generated by Django 5.0.4 on 2025-01-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_law_assesment_remove_answer_assesment_id_and_more'),
    ]

    operations = [
        # removed the auto-generated removeFields operations since the whole model is deleted below
        # deleting a model with no fields causes an operational error
        migrations.DeleteModel(
            name='Law',
        ),
        migrations.DeleteModel(
            name='Phase4Answer',
        ),
    ]
